import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'

export default function Home() {
  const [location, setLocation] = useState("")

  const fetchRandomData = async () => {
    const response = await fetch(`/api/getRandom/${location}`);
    // INTERNAL SERVER ERROR CATCHER
    if(response.status === 500) return 500;
    const businesses = await response.json();
    return businesses.businesses;
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <input type='text' value={location} onChange={(e) => setLocation(e.target.value)}/>
        <button onClick={fetchRandomData}>
          test
        </button>
      </main>
    </>
  )
}
